# .github/workflows/stop-ec2.yml

name: 'Stop Citygate EC2 Environment'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 0-4'

permissions:
  id-token: write
  contents: read

jobs:
  stop-ec2-instances:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # CORRECTED: The Role ARN now matches the start workflow
          role-to-assume: arn:aws:iam::588738602727:role/GitHubActions-Citygate-EC2-Role
          aws-region: eu-west-1

      - name: Stop EC2 Instances
        run: |
          # NOTE: Ensure your EC2 tag value is exactly "CitygateDev" (case-sensitive)
          echo "Fetching EC2 instances with tag Environment=CitygateDev..."
          INSTANCE_IDS=$(aws ec2 describe-instances \
            --filters "Name=tag:Environment,Values=CitygateDev" "Name=instance-state-name,Values=running" \
            --query "Reservations[*].Instances[*].InstanceId" \
            --output text)

          if [ -z "$INSTANCE_IDS" ]; then
            echo "No running EC2 instances found with the specified tag. Nothing to do."
          else
            echo "Stopping EC2 instances: $INSTANCE_IDS"
            aws ec2 stop-instances --instance-ids $INSTANCE_IDS
          fi